import type { Metadata } from "next";
import "./globals.css";
import MainLayoutSection from "@/component/General/MainLayout";


export const metadata: Metadata = {
  title: "Seekers of His Kingdom",
  description: "Generated by Seekers of His Kingdom",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
 <body className="">
     <MainLayoutSection>
        {children}
         </MainLayoutSection>
      </body>
    </html>
  );
}