import type { Metadata } from "next";
import "./globals.css";
import MainLayoutSection from "@/component/General/MainLayout";

// Site info
const SITE_NAME = "Seekers of His Kingdom";
const SITE_DESCRIPTION = "Generated by Seekers of His Kingdom";
const SITE_URL = "https://church-website-ruby-tau.vercel.app/";
const TWITTER_HANDLE = "";

export const metadata: Metadata = {
  title: { default: SITE_NAME, template: `%s | ${SITE_NAME}` },
  description: SITE_DESCRIPTION,
  keywords: ["church", "fellowship", "God", "Bible", "Seeker_of_his_kingdom", "Seeker_of_his_kingdom"],
  authors: [{ name: "Seeker_of_his_kingdom" }, { name: "Seeker_of_his_kingdom" }],
  creator: "Seeker_of_his_kingdom",
  publisher: "Seeker_of_his_kingdom",
  metadataBase: new URL(SITE_URL),
  openGraph: {
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    siteName: SITE_NAME,
    images: [
      {
        url: `${SITE_URL}/`,
        width: 1200,
        height: 630,
        alt: SITE_NAME,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    creator: TWITTER_HANDLE,
    images: [
      {
        url: `${SITE_URL}/`,
        alt: SITE_NAME,
      },
    ],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/" },
      { url: "/", sizes: "16x16", type: "image/png" },
      { url: "/", sizes: "32x32", type: "image/png" },
    ],
    apple: [{ url: "/" }],
  },
  manifest: "/site.webmanifest",
  themeColor: "#ffffff",
  viewport: "width=device-width, initial-scale=1",
  verification: {
    google: "",
  },
  alternates: {
    canonical: SITE_URL,
    languages: { "en-US": SITE_URL, "x-default": SITE_URL },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
 <body className="">
     <MainLayoutSection>
        {children}
         </MainLayoutSection>
      </body>
    </html>
  );
}